<?php

namespace DinoCompareBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DinoDataRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DinoDataRepository extends EntityRepository
{
    public function findDinoByName($text)
    {
        $dino = $this->getEntityManager()->createQuery(
            'SELECT p from DinoCompareBundle:DinoData p WHERE p.name LIKE :text')
            ->setParameter('text', '%' . $text . '%')
            ->getResult();

        return $dino;
    }
}
