<?php

namespace DinoCompareBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PeriodRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PeriodRepository extends EntityRepository
{
}
